# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-17 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='idc',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='monitor_data',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
