# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-23 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190517_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor_data',
            name='datetime',
            field=models.IntegerField(max_length=12),
        ),
    ]
